openapi: 3.0.3
info:
  title: Products Ruby API
  description: This is an API to manage products
  license:
    name: MIT
    url: https://choosealicense.com/licenses/mit/
  version: 1.0.0

servers:
  - url: http://localhost:3000/v1

tags:
  - name: Login
    description: Operations for user login
  - name: Products
    description: Operations related to products

paths:
  /login:
    post:
      tags:
        - Login
      summary: User login to obtain JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Invalid credentials

  /products:
    get:
      tags:
        - Products
      summary: Get a list of products
      security:
        - BearerToken: []
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      tags:
        - Products
      summary: Add a new product
      security:
        - BearerToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '202':
          description: Product creation initiated
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /products/{productId}:
    get:
      tags:
        - Products
      summary: Get details of a specific product
      security:
        - BearerToken: []
      parameters:
        - name: productId
          in: path
          required: true
          description: The ID of the product to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found

components:
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer

  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - name
